### PR TITLE
Sishida patch 1

### PR DESCRIPTION
**Pull request by sishida**

### CODE REVIEW

**Comment by sishida** [comment]
111. Do you enable the mpHealth-1.0 feature, or does part of the program do so? What is enabling this feature?
159. What is using the property in this file?
163. How does the line of code here relate to the paragraph above it?
192. What is applying the condition?
221. What do we mean by turning the service "down"? I want to avoid using Latin abbreviations like "i.e." and want to come up with an accurate alternative.

**Comment by Ahmad-Ayyoub** [comment]
First: you probably have cloned the repo at the wrong time ;). Sorry we should have told you. The latest changes on this guide were reverted. So The only thing should be changing is README. In your PR, still the reverted changes are pushed. 

111. It is provided. The user does not enable it. 
159. InventoryConfig object is used to read that property in this file
163. this line of code is what the property is. so i am saying hey -> this is the property i am talking about
192. Change The same condition applies -> The same thing applies. I am trying to say the same way you did in the previous function, do it in this function as well. 
221. when i say a service is down -> that means : the service is no longer working because it is currently in maintenance or something went wrong -> so rather than saying all of that we say service is down.

**Comment by Ahmad-Ayyoub** [comment]
Thank you a lot @sishida

**Comment by sishida** [comment]
@Ahmad-Ayyoub I think the README file is the only file that I edited intentionally...are the other files updated automatically as part of metadata or something? Anyway, feel free to edit over those! As long as my changes from the README got in, I'm good! ;)

I'll work on your other comments tomorrow. Thank you!

**Comment by Ahmad-Ayyoub** [comment]
Yes. I understand that you only touched on README. but I meant you need to remove the other commits as well. Since it is already in this PR: https://github.com/OpenLiberty/draft-guide-microprofile-health/pull/17. If you need help with that let me know.

**Pull request closed without merging**
